title: "上がるファスナー"
author: "すいと"
twitter_username: "suito_kig"
description: "Made with Jekyll"
permalink: /:title/
lang: "ja"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
url: "https://suito-kig.github.io/blog"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: X, icon: x-twitter, url: "https://x.com/suito_kig"}
  - {title: Bluesky, icon: bluesky, url: "https://bsky.app/profile/suito-kig.bsky.social"}
  - {title: Discord, icon: discord, url: "https://discordapp.com/users/1174343048499568753"}
  - {title: Github, icon: github, url: "https://github.com/suito-kig"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-gist
 - jekyll-seo-tag